apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monica.fullname" . }}
  labels:
    {{- include "monica.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.app.key }}
  app_key: {{ .Values.app.key | b64enc | quote }}
  {{- end }}
  {{- if .Values.hash.salt }}
  hash_salt: {{ .Values.hash.salt | b64enc | quote }}
  {{- end }}
  {{- if .Values.db.password }}
  db_password: {{ .Values.db.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.db.test.password }}
  db_test_password: {{ .Values.db.test.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.mail.password }}
  mail_password: {{ .Values.mail.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.aws.key }}
  aws_key: {{ .Values.aws.key | b64enc | quote }}
  {{- end }}
  {{- if .Values.aws.secret }}
  aws_secret: {{ .Values.aws.secret | b64enc | quote }}
  {{- end }}
  {{- if .Values.mobile.client_secret }}
  mobile_client_secret: {{ .Values.mobile.client_secret | b64enc | quote }}
  {{- end }}
  {{- if .Values.geolocation.location_iq_api_key }}
  location_iq_api_key: {{ .Values.geolocation.location_iq_api_key | b64enc | quote }}
  {{- end }}
  {{- if .Values.weather.darksky_api_key }}
  darksky_api_key: {{ .Values.weather.darksky_api_key | b64enc | quote }}
  {{- end }}